trigger:
- master

jobs:
- job: Code_Quality
  pool:
    vmImage: 'Ubuntu 16.04'
  container: norionomura/swiftlint:swift-5
  timeoutInMinutes: 5
  steps:
  - script: |
     set -o pipefail
      swiftlint lint --strict
    displayName: 'SwiftLint'
